### ISSUE TITLE
`startup_commands` fails when config value is a single string.

### ISSUE THREAD

**Issue by gvoysey** [dbcli/litecli#176]
Using litecli version 1.10.1, installed with pipx on linux; base python is a pyenv-installed 3.10.10.

Given the following contents of `~/.config/litecli/config`:
```toml
[startup_commands]
commands = ".tables"
```
loading litecli fails:
```text
.
Could not execute all startup commands:
Not connected to database.
(none)>
```

If the config is changed to add a trailing comma:
```toml
[startup_commands]
commands = ".tables",
```
then the `.tables` command is correctly executed.

I suspect this is because without the comma, python is iterating the over the string `".tables"`, not the list `[".tables",]`:  https://github.com/dbcli/litecli/blob/9d5bcf0ba17fd0562309164175d7db1a54f85464/litecli/main.py#L591-L596

Adding a print above L592 confirms.  
Without a comma: 
`self.startup_commands={'commands': '.tables'}`

With a comma:
`self.startup_commands={'commands': ['.tables']}`
